package koble

var VERSION = "0.0.1"

var DEFAULT_STARTUP = `#!/bin/bash

# Machine.startup - generated by koble machine add
# This is a script that will run when the machine boots

`

var SHARED_STARTUP = `#!/bin/bash

# shared.startup - generated by koble machine add
# This is a script that will run for all machines in the lab
# It will run before the machine specific .startup script

`
