= Koble

image:https://img.shields.io/github/v/release/b177y/koble?include_prereleases&style=flat-square[link="https://github.com/b177y/koble/releases"]
image:https://img.shields.io/github/license/b177y/koble?style=flat-square[link="https://github.com/b177y/koble/blob/main/LICENSE.txt"]
image:https://img.shields.io/badge/godoc-reference-blue.svg?style=flat-square[link="https://pkg.go.dev/github.com/b177y/koble"]

== Overview

Koble is a project for creating virtual network devices (routers, switches, servers etc)
which can be connected to form a full network on a single host machine.
This can be useful for running network related experiments or for education.
Koble machines can be User-mode Linux instances or rootless Podman containers
which are lightweight and do not require root privileges to run.

== Quick Start

The install script for Ubuntu 20.04 can be found
link:https://github.com/b177y/koble/releases/download/v0.1/install.sh[here].

This will install Koble and the dependencies for both the Podman and UML driver.

ifdef::env-github[]
For distros other than Ubuntu 20.04, see the instructions in the
link:https://koble.b177y.dev/koble-docs/0.1/installation.html[installation guide].
endif::[]
ifndef::env-github[]
For distros other than Ubuntu 20.04, see the instructions in the
xref:installation.adoc[installation guide].
endif::[]

== Usage

[source]
----
Koble is a network emulation tool

Usage:
  koble [command]

Available Commands:
  add         add a new machine to a lab
  attach      attach to the main tty of a machine
  completion  Generate the autocompletion script for the specified shell
  destroy     force stop and remove a machine
  exec        run a command on a machine
  help        Help about any command
  info        get info about a machine
  lab         manage labs
  list        list machines
  logs        get logs from a machine
  machine     manage machines
  net         manage networks
  remove      remove a machine
  shell       get a shell on a machine
  start       start a machine
  stop        stop a machine

Flags:
      --driver string      name of driver to use
  -h, --help               help for koble
      --namespace string   namespace to use
      --no-color           disable coloured output
      --plain              disable interactive and coloured output
      --quiet              only show errors in log errors
  -v, --verbose count      verbose output
      --version            version for koble

Additional help topics:
  koble driver     manage a koble driver

Use "koble [command] --help" for more information about a command.
----
