= User Trials

== Overview

The purpose of this project is to explore the use of containers within
network emulation tools.
I have developed Koble as a 'modern' Netkit alternative,
which gives you the ability to use either Podman containers
or User Mode Linux virtual machines (which are used for the original Netkit).
You don't need any understanding of how these technologies work for the purpose
of this task.

== Google Survey

You will give your feedback via a google survey.
The link for this will be given to you in the session.

== Install

CAUTION: This only covers installation for Ubuntu 20.04.
This will not work for Ubuntu 21.04.
It won't work for CentOS.
It won't work for Arch.
If you're not using Ubuntu 20.04 use the manual install guide
xref:installation.adoc#_manual_installation[here].

Firstly you will need to install `koble` on an Ubuntu 20.04 virtual machine.
This can be done on the same VM that you use for Netkit, but it is recommended
that you take a snapshot of the VM before the task so you can easily roll back
if you face any problems.

To install the tool and it's dependencies on Ubuntu 20.04 you can download
and execute this install script:

The install script for can be found
link:https://github.com/b177y/koble/releases/download/v0.1/install.sh[here].

[source,sh]
----
wget https://github.com/b177y/koble/releases/download/v0.1/install.sh

# manually inspect installer, check code is trusted before executing
less install.sh

bash install.sh

# after you have run the install you will need to reload your shell configuration
# or start a new terminal
source ~/.bashrc # or ~/.zshrc if you use zsh
----

== Tasks

* xref:LABS:abr.adoc[ABR Lab]
* Answer section 1 of survey (ABR Lab Feedback)
* Start converting the lab that you submitted for ISS CW2 to use Koble instead of
Netkit.
This will involve creating a `lab.yml` file with all your machines.
Looking through the *Usage* section of this docs site should help you
getting started with Koble.
For complex labs this is a big task so you could pick one or two features of the lab
to try to get working.
Even if you don't get far through this,
giving any feedback on the google form is useful for improving Koble for future students.
* Answer section 2 of survey (ISS CW2 Lab)
* Answer section 3 of survey (Additional Feedback)

NOTE: Koble is still in beta and is not completely stable yet,
you are likely to find both bugs and missing functionality.
Please mention any problems you have in the feedback form
so these can be improved for future versions.
