= UML Shim

== Overview

UML Shim wraps a command with a 'supervisor' process which fills a specified directory with:

* machine.log - a log of the all stdout and stderr from the process
* state - a file containing the state of the process (booting, running, exited)
* exitcode - a file containing the exit code of the process once it finishes
* attach.sock - a unix socket which (multiple) clients can attach to,
giving access to stdin, stdout and stderr of the process
* umlshim.log - a log file with debugging information from the shim

Although the shim can wrap any process,
it is designed to wrap Usermode Linux kernel processes.
The 'state' file is updated from booting to running by looking for
an output which is specific to Netkit UML.

== Usage

=== CLI Examples

Basic examples can be found in the `examples` directory.

To run the shim:

[source,sh]
----
go run examples/main.go -d DIRECTORY COMMAND
----

To connect to the session:

[source,sh]
----
go run examples/client.go -d DIRECTORY
----

=== Usage Within Code

To use the shim within a library you need docker's `reexec` package.

Register the shim function as a reexec function:

[source,go]
----
func init() {
	reexec.Register("umlShim", shim.RunShim)
	if reexec.Init() {
		os.Exit(0)
	}
}
----

To call the shim:

[source,go]
----
c := reexec.Command("umlShim", "/DIR/FOR/ATTACHSOCK", "COMMAND", "Arg1", "Arg2", ...)
----
