## default namespace to use
## when in a lab directory the namespace will be md5sum(/path/to/lab) instead of the default
## this can be overriden in lab.yml or with --namespace
# namespace: "GLOBAL"

## driver settings
# driver:
  ## driver to use (options are 'uml' or 'podman')
  # name: podman
  ## override default podman driver config
  # podman:
    ## Use custom podman URI (e.g. remote socket, run under different user)
    # uri: "unix://run/user/1000/podman/podman.sock"
  
  ## override default uml driver config
  # uml:
    ## directory to use for kernel binary, filesystem and overlay disks
    # storage: ~/.local/share/uml
    ## name of kernel binary within {storage}/kernel
    # kernel: koble-kernel
    ## name of filesystem base image within {storage}/images
    # fs: koble-fs

## Add custom terminals which can then be chosen using the terminal option
## if a terminal already exists, the command and options will override the defaults
# terminal:
  ## default terminal to use
  # default: "gnome"
  ## overrides for terminal 'tmux'
  # tmux:
  #   options:
  #     session: "koble-custom"
  # attach: "gnome" # uses default if no option set
  # shell: "gnome" # uses default if no option set
  # exec: "this" # defaults to 'this' (launch in current tty)
  # lab_start: "gnome" # uses default if no option set
  # machine_start: "gnome" # uses default if no option set
