## default namespace to use
## when in a lab directory the namespace will be md5sum(/path/to/lab) instead of the default
## this can be overriden in lab.yml or with --namespace
# namespace: "GLOBAL"

# driver settings
driver:
  name: podman
  ## Use uml driver instead of default podman
  # name: uml

  # override default podman driver config
  # podman:
    ## Use custom podman URI (e.g. remote socket, run under different user)
    # uri: "unix://run/user/1000/podman/podman.sock"
  
  # uml:
    # storage: ~/.local/share/netkit/uml
    # kernel: netkit-kernel-5.4
    # fs: netkit-fs-focal

## Add custom terminals which can then be chosen using the terminal option
## if a terminal already exists, the command and options will override the defaults
# terminal:
#   name: "alacritty"
#   tmux:
#     options:
#       session: "koble-custom"
#   alacritty:
#     command:
#       - "alacritty"
#       - "--hold"
#       - "-e"
#       - "{{ .Command }}"
